import {MigrationInterface, QueryRunner} from "typeorm";

export class tournament1640580361357 implements MigrationInterface {
    name = 'tournament1640580361357'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query("CREATE TABLE `bracket` (`ID` int NOT NULL AUTO_INCREMENT, `name` varchar(255) NOT NULL, `tournamentID` int NULL, `mappoolID` int NULL, UNIQUE INDEX `REL_09f7c79304d58cb58487259887` (`mappoolID`), PRIMARY KEY (`ID`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `group` (`ID` int NOT NULL AUTO_INCREMENT, `tournamentID` int NULL, `mappoolID` int NULL, PRIMARY KEY (`ID`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `qualifier` (`ID` int NOT NULL AUTO_INCREMENT, `time` timestamp NOT NULL, `mp` int NULL, `public` tinyint NOT NULL DEFAULT 0, `tournamentID` int NULL, `mappoolID` int NULL, `refereeID` int NULL, PRIMARY KEY (`ID`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `match_play` (`ID` int NOT NULL AUTO_INCREMENT, `score` int NOT NULL, `mods` varchar(255) NOT NULL, `misses` int NOT NULL, `combo` int NOT NULL, `accuracy` float NOT NULL, `FC` tinyint NOT NULL DEFAULT 0, `fail` tinyint NOT NULL DEFAULT 0, `userID` int NULL, `beatmapID` int NULL, `qualifierID` int NULL, PRIMARY KEY (`ID`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `match_set` (`ID` int NOT NULL AUTO_INCREMENT, `teamAScore` int NOT NULL DEFAULT '0', `teamBScore` int NOT NULL DEFAULT '0', `matchID` int NULL, `winnerID` int NULL, PRIMARY KEY (`ID`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `match_beatmap` (`ID` int NOT NULL AUTO_INCREMENT, `status` enum ('0', '1') NOT NULL DEFAULT '0', `beatmapID` int NULL, `matchID` int NULL, `setID` int NULL, `winnerID` int NULL, PRIMARY KEY (`ID`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `match` (`ID` int NOT NULL AUTO_INCREMENT, `matchID` varchar(255) NOT NULL, `time` timestamp NOT NULL, `teamAScore` int NOT NULL DEFAULT '0', `teamBScore` int NOT NULL DEFAULT '0', `forfeit` tinyint NOT NULL DEFAULT 0, `potential` tinyint NOT NULL DEFAULT 0, `twitch` varchar(255) NULL, `mp` int NULL, `bestof` tinyint NOT NULL, `bracketID` int NULL, `groupID` int NULL, `teamAID` int NULL, `teamBID` int NULL, `firstID` int NULL, `winnerID` int NULL, `refereeID` int NULL, `streamerID` int NULL, PRIMARY KEY (`ID`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `team_invitation` (`ID` int NOT NULL AUTO_INCREMENT, `status` enum ('0', '1', '2', '3') NOT NULL DEFAULT '0', `dateCreated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, `lastUpdate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, `targetID` int NULL, `teamID` int NULL, PRIMARY KEY (`ID`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `team` (`ID` int NOT NULL AUTO_INCREMENT, `creation` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, `name` varchar(255) NOT NULL, `slug` varchar(255) NOT NULL, `teamAvatarUrl` varchar(255) NULL DEFAULT NULL, `membersAmount` int NOT NULL DEFAULT '1', `averageBWS` int NOT NULL, `rank` int NULL, `seed` char NULL, `role` varchar(255) NOT NULL, `demerits` int NOT NULL DEFAULT '0', `qualifierID` int NULL, `tournamentID` int NULL, PRIMARY KEY (`ID`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `tournament` (`ID` int NOT NULL AUTO_INCREMENT, `name` varchar(255) NOT NULL, `size` int NOT NULL, `eligibleTeamSize` int NOT NULL, `maximumTeamSize` int NOT NULL, `doubleElim` tinyint NOT NULL DEFAULT 1, `useBWS` tinyint NOT NULL DEFAULT 1, `registrationStart` timestamp NOT NULL, `registrationEnd` timestamp NOT NULL, PRIMARY KEY (`ID`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `mappool` (`ID` int NOT NULL AUTO_INCREMENT, `name` varchar(255) NOT NULL, `tournamentID` int NULL, PRIMARY KEY (`ID`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `mappool_beatmap` (`ID` int NOT NULL AUTO_INCREMENT, `mod` enum ('0', '1', '2', '3', '4', '5') NOT NULL DEFAULT '0', `slot` int NOT NULL, `mappoolID` int NULL, `beatmapID` int NULL, PRIMARY KEY (`ID`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `badge` (`ID` int NOT NULL AUTO_INCREMENT, `description` varchar(255) NOT NULL, `imageName` varchar(255) NOT NULL, `userID` int NULL, PRIMARY KEY (`ID`)) ENGINE=InnoDB");
        await queryRunner.query("ALTER TABLE `user` ADD `pp` float NULL");
        await queryRunner.query("ALTER TABLE `user` ADD `rank` int NULL");
        await queryRunner.query("ALTER TABLE `user` ADD `teamID` int NULL");
        await queryRunner.query("ALTER TABLE `user` ADD `teamCaptainID` int NULL");
        await queryRunner.query("ALTER TABLE `user` ADD UNIQUE INDEX `IDX_40d2ad0a76018199424a6ec399` (`teamCaptainID`)");
        await queryRunner.query("ALTER TABLE `demerit_report` CHANGE `reportDate` `reportDate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP");
        await queryRunner.query("ALTER TABLE `nomination` CHANGE `lastReviewedAt` `lastReviewedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP");
        await queryRunner.query("ALTER TABLE `guest_request` CHANGE `status` `status` enum ('0', '1', '2', '3') NOT NULL DEFAULT '0'");
        await queryRunner.query("ALTER TABLE `user` CHANGE `lastLogin` `lastLogin` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP");
        await queryRunner.query("ALTER TABLE `user` CHANGE `discordUserid` `discordUserid` varchar(255) NULL DEFAULT NULL");
        await queryRunner.query("ALTER TABLE `user` CHANGE `discordLastverified` `discordLastverified` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP");
        await queryRunner.query("ALTER TABLE `user` CHANGE `osuUserid` `osuUserid` varchar(255) NULL DEFAULT NULL");
        await queryRunner.query("ALTER TABLE `user` CHANGE `osuLastverified` `osuLastverified` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP");
        await queryRunner.query("CREATE UNIQUE INDEX `REL_40d2ad0a76018199424a6ec399` ON `user` (`teamCaptainID`)");
        await queryRunner.query("ALTER TABLE `bracket` ADD CONSTRAINT `FK_6a69554fae345ac89261864bc35` FOREIGN KEY (`tournamentID`) REFERENCES `tournament`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `bracket` ADD CONSTRAINT `FK_09f7c79304d58cb584872598877` FOREIGN KEY (`mappoolID`) REFERENCES `mappool`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `group` ADD CONSTRAINT `FK_f91304c6a5670996ed42d2bd76f` FOREIGN KEY (`tournamentID`) REFERENCES `tournament`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `group` ADD CONSTRAINT `FK_6ef9d96c02c07df3390571b76c2` FOREIGN KEY (`mappoolID`) REFERENCES `mappool`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `qualifier` ADD CONSTRAINT `FK_d6d5347a06dbbe7a95d795b3677` FOREIGN KEY (`tournamentID`) REFERENCES `tournament`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `qualifier` ADD CONSTRAINT `FK_b434a19d9de650c03e696fd4cc1` FOREIGN KEY (`mappoolID`) REFERENCES `mappool`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `qualifier` ADD CONSTRAINT `FK_515f81b3d2669a9ef93fe333b48` FOREIGN KEY (`refereeID`) REFERENCES `user`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `match_play` ADD CONSTRAINT `FK_5dc2803f10295f00da238c05f6c` FOREIGN KEY (`userID`) REFERENCES `user`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `match_play` ADD CONSTRAINT `FK_a22b9ba7ea5eb481bc9252d3d68` FOREIGN KEY (`beatmapID`) REFERENCES `match_beatmap`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `match_play` ADD CONSTRAINT `FK_c34a3a2c405b4d3616cfa849e28` FOREIGN KEY (`qualifierID`) REFERENCES `qualifier`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `match_set` ADD CONSTRAINT `FK_cfa8399331629382462b4cd300a` FOREIGN KEY (`matchID`) REFERENCES `match`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `match_set` ADD CONSTRAINT `FK_c7205b44d28aaa9af40143b24c8` FOREIGN KEY (`winnerID`) REFERENCES `team`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `match_beatmap` ADD CONSTRAINT `FK_11e09a35b6d437a0a3bcfa8a9b7` FOREIGN KEY (`beatmapID`) REFERENCES `mappool_beatmap`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `match_beatmap` ADD CONSTRAINT `FK_2c3cb8444e0e19079609099a9b1` FOREIGN KEY (`matchID`) REFERENCES `match`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `match_beatmap` ADD CONSTRAINT `FK_2732bd4673df6ed34f3ab7d1a81` FOREIGN KEY (`setID`) REFERENCES `match_set`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `match_beatmap` ADD CONSTRAINT `FK_e2b7364d8e1858a17ea446331b6` FOREIGN KEY (`winnerID`) REFERENCES `team`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `match` ADD CONSTRAINT `FK_7e3e59ee9b03d670202170fe0b6` FOREIGN KEY (`bracketID`) REFERENCES `bracket`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `match` ADD CONSTRAINT `FK_933aaa570dec0da0029cbfafb8d` FOREIGN KEY (`groupID`) REFERENCES `group`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `match` ADD CONSTRAINT `FK_76a3691d7b4928c1a01ac71b623` FOREIGN KEY (`teamAID`) REFERENCES `team`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `match` ADD CONSTRAINT `FK_97e935a4cab6ec20ea16f0f0643` FOREIGN KEY (`teamBID`) REFERENCES `team`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `match` ADD CONSTRAINT `FK_7a04fc3445a0738c5e461733f5e` FOREIGN KEY (`firstID`) REFERENCES `team`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `match` ADD CONSTRAINT `FK_11d6d66ef011501312035df46ff` FOREIGN KEY (`winnerID`) REFERENCES `team`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `match` ADD CONSTRAINT `FK_15a67b26bb5527a818ab14ce5c7` FOREIGN KEY (`refereeID`) REFERENCES `user`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `match` ADD CONSTRAINT `FK_2fdec8e86184066e0481e3b10ff` FOREIGN KEY (`streamerID`) REFERENCES `user`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `team_invitation` ADD CONSTRAINT `FK_f4c0185ed25cce5c16a53f0af90` FOREIGN KEY (`targetID`) REFERENCES `user`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `team_invitation` ADD CONSTRAINT `FK_f4d79e0e60676e441d81a10a8d1` FOREIGN KEY (`teamID`) REFERENCES `team`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `team` ADD CONSTRAINT `FK_54a3e0e168b6a121d3c3cd74ce5` FOREIGN KEY (`qualifierID`) REFERENCES `qualifier`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `team` ADD CONSTRAINT `FK_c4b9144071b6221aa1aa52ec18a` FOREIGN KEY (`tournamentID`) REFERENCES `tournament`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `mappool` ADD CONSTRAINT `FK_bc01172bc24411feacabc3cc896` FOREIGN KEY (`tournamentID`) REFERENCES `tournament`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `mappool_beatmap` ADD CONSTRAINT `FK_74ff30fa1fbeda5aa3f1090fc90` FOREIGN KEY (`mappoolID`) REFERENCES `mappool`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `mappool_beatmap` ADD CONSTRAINT `FK_5bfb31c4bbc22f2282411426877` FOREIGN KEY (`beatmapID`) REFERENCES `beatmap`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `user` ADD CONSTRAINT `FK_473d07b509b71a919cbc9a87bf1` FOREIGN KEY (`teamID`) REFERENCES `team`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `user` ADD CONSTRAINT `FK_40d2ad0a76018199424a6ec3991` FOREIGN KEY (`teamCaptainID`) REFERENCES `team`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `badge` ADD CONSTRAINT `FK_12135fb2717c6c684b0e5afe0b1` FOREIGN KEY (`userID`) REFERENCES `user`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION");
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query("ALTER TABLE `badge` DROP FOREIGN KEY `FK_12135fb2717c6c684b0e5afe0b1`");
        await queryRunner.query("ALTER TABLE `user` DROP FOREIGN KEY `FK_40d2ad0a76018199424a6ec3991`");
        await queryRunner.query("ALTER TABLE `user` DROP FOREIGN KEY `FK_473d07b509b71a919cbc9a87bf1`");
        await queryRunner.query("ALTER TABLE `mappool_beatmap` DROP FOREIGN KEY `FK_5bfb31c4bbc22f2282411426877`");
        await queryRunner.query("ALTER TABLE `mappool_beatmap` DROP FOREIGN KEY `FK_74ff30fa1fbeda5aa3f1090fc90`");
        await queryRunner.query("ALTER TABLE `mappool` DROP FOREIGN KEY `FK_bc01172bc24411feacabc3cc896`");
        await queryRunner.query("ALTER TABLE `team` DROP FOREIGN KEY `FK_c4b9144071b6221aa1aa52ec18a`");
        await queryRunner.query("ALTER TABLE `team` DROP FOREIGN KEY `FK_54a3e0e168b6a121d3c3cd74ce5`");
        await queryRunner.query("ALTER TABLE `team_invitation` DROP FOREIGN KEY `FK_f4d79e0e60676e441d81a10a8d1`");
        await queryRunner.query("ALTER TABLE `team_invitation` DROP FOREIGN KEY `FK_f4c0185ed25cce5c16a53f0af90`");
        await queryRunner.query("ALTER TABLE `match` DROP FOREIGN KEY `FK_2fdec8e86184066e0481e3b10ff`");
        await queryRunner.query("ALTER TABLE `match` DROP FOREIGN KEY `FK_15a67b26bb5527a818ab14ce5c7`");
        await queryRunner.query("ALTER TABLE `match` DROP FOREIGN KEY `FK_11d6d66ef011501312035df46ff`");
        await queryRunner.query("ALTER TABLE `match` DROP FOREIGN KEY `FK_7a04fc3445a0738c5e461733f5e`");
        await queryRunner.query("ALTER TABLE `match` DROP FOREIGN KEY `FK_97e935a4cab6ec20ea16f0f0643`");
        await queryRunner.query("ALTER TABLE `match` DROP FOREIGN KEY `FK_76a3691d7b4928c1a01ac71b623`");
        await queryRunner.query("ALTER TABLE `match` DROP FOREIGN KEY `FK_933aaa570dec0da0029cbfafb8d`");
        await queryRunner.query("ALTER TABLE `match` DROP FOREIGN KEY `FK_7e3e59ee9b03d670202170fe0b6`");
        await queryRunner.query("ALTER TABLE `match_beatmap` DROP FOREIGN KEY `FK_e2b7364d8e1858a17ea446331b6`");
        await queryRunner.query("ALTER TABLE `match_beatmap` DROP FOREIGN KEY `FK_2732bd4673df6ed34f3ab7d1a81`");
        await queryRunner.query("ALTER TABLE `match_beatmap` DROP FOREIGN KEY `FK_2c3cb8444e0e19079609099a9b1`");
        await queryRunner.query("ALTER TABLE `match_beatmap` DROP FOREIGN KEY `FK_11e09a35b6d437a0a3bcfa8a9b7`");
        await queryRunner.query("ALTER TABLE `match_set` DROP FOREIGN KEY `FK_c7205b44d28aaa9af40143b24c8`");
        await queryRunner.query("ALTER TABLE `match_set` DROP FOREIGN KEY `FK_cfa8399331629382462b4cd300a`");
        await queryRunner.query("ALTER TABLE `match_play` DROP FOREIGN KEY `FK_c34a3a2c405b4d3616cfa849e28`");
        await queryRunner.query("ALTER TABLE `match_play` DROP FOREIGN KEY `FK_a22b9ba7ea5eb481bc9252d3d68`");
        await queryRunner.query("ALTER TABLE `match_play` DROP FOREIGN KEY `FK_5dc2803f10295f00da238c05f6c`");
        await queryRunner.query("ALTER TABLE `qualifier` DROP FOREIGN KEY `FK_515f81b3d2669a9ef93fe333b48`");
        await queryRunner.query("ALTER TABLE `qualifier` DROP FOREIGN KEY `FK_b434a19d9de650c03e696fd4cc1`");
        await queryRunner.query("ALTER TABLE `qualifier` DROP FOREIGN KEY `FK_d6d5347a06dbbe7a95d795b3677`");
        await queryRunner.query("ALTER TABLE `group` DROP FOREIGN KEY `FK_6ef9d96c02c07df3390571b76c2`");
        await queryRunner.query("ALTER TABLE `group` DROP FOREIGN KEY `FK_f91304c6a5670996ed42d2bd76f`");
        await queryRunner.query("ALTER TABLE `bracket` DROP FOREIGN KEY `FK_09f7c79304d58cb584872598877`");
        await queryRunner.query("ALTER TABLE `bracket` DROP FOREIGN KEY `FK_6a69554fae345ac89261864bc35`");
        await queryRunner.query("DROP INDEX `REL_40d2ad0a76018199424a6ec399` ON `user`");
        await queryRunner.query("ALTER TABLE `user` CHANGE `osuLastverified` `osuLastverified` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP()");
        await queryRunner.query("ALTER TABLE `user` CHANGE `osuUserid` `osuUserid` varchar(255) NULL");
        await queryRunner.query("ALTER TABLE `user` CHANGE `discordLastverified` `discordLastverified` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP()");
        await queryRunner.query("ALTER TABLE `user` CHANGE `discordUserid` `discordUserid` varchar(255) NULL");
        await queryRunner.query("ALTER TABLE `user` CHANGE `lastLogin` `lastLogin` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP()");
        await queryRunner.query("ALTER TABLE `guest_request` CHANGE `status` `status` enum ('0', '1', '2') NOT NULL DEFAULT '0'");
        await queryRunner.query("ALTER TABLE `nomination` CHANGE `lastReviewedAt` `lastReviewedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP()");
        await queryRunner.query("ALTER TABLE `demerit_report` CHANGE `reportDate` `reportDate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP()");
        await queryRunner.query("ALTER TABLE `user` DROP INDEX `IDX_40d2ad0a76018199424a6ec399`");
        await queryRunner.query("ALTER TABLE `user` DROP COLUMN `teamCaptainID`");
        await queryRunner.query("ALTER TABLE `user` DROP COLUMN `teamID`");
        await queryRunner.query("ALTER TABLE `user` DROP COLUMN `rank`");
        await queryRunner.query("ALTER TABLE `user` DROP COLUMN `pp`");
        await queryRunner.query("DROP TABLE `badge`");
        await queryRunner.query("DROP TABLE `mappool_beatmap`");
        await queryRunner.query("DROP TABLE `mappool`");
        await queryRunner.query("DROP TABLE `tournament`");
        await queryRunner.query("DROP TABLE `team`");
        await queryRunner.query("DROP TABLE `team_invitation`");
        await queryRunner.query("DROP TABLE `match`");
        await queryRunner.query("DROP TABLE `match_beatmap`");
        await queryRunner.query("DROP TABLE `match_set`");
        await queryRunner.query("DROP TABLE `match_play`");
        await queryRunner.query("DROP TABLE `qualifier`");
        await queryRunner.query("DROP TABLE `group`");
        await queryRunner.query("DROP INDEX `REL_09f7c79304d58cb58487259887` ON `bracket`");
        await queryRunner.query("DROP TABLE `bracket`");
    }

}
