import { MigrationInterface, QueryRunner } from "typeorm";

export class tournamentMigration1683306860711 implements MigrationInterface {
    name = "tournamentMigration1683306860711";

    public async up (queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`mappool_map_history\` (\`ID\` int NOT NULL AUTO_INCREMENT, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`artist\` varchar(255) NULL, \`title\` varchar(255) NULL, \`difficulty\` varchar(255) NULL, \`link\` varchar(255) NULL, \`createdByID\` int NULL, \`mappoolMapID\` int NULL, \`beatmapID\` int NULL, PRIMARY KEY (\`ID\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`mappool_map_skill\` (\`ID\` int NOT NULL AUTO_INCREMENT, \`rating\` int NOT NULL, \`skill\` enum ('0', '1', '2', '3', '4', '5', '6', '7', '8') NOT NULL, \`userID\` int NULL, \`mappoolMapID\` int NULL, PRIMARY KEY (\`ID\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`mappool_map_weight\` (\`ID\` int NOT NULL AUTO_INCREMENT, \`weight\` int NOT NULL, \`skill\` enum ('0', '1', '2', '3', '4', '5', '6', '7', '8') NOT NULL, \`userID\` int NULL, \`mappoolMapID\` int NULL, PRIMARY KEY (\`ID\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`tournament_role\` (\`ID\` int NOT NULL AUTO_INCREMENT, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`roleID\` varchar(255) NOT NULL, \`roleType\` enum ('0', '1', '2', '3', '4', '5', '6', '7', '8') NOT NULL, \`createdByID\` int NULL, \`tournamentID\` int NULL, PRIMARY KEY (\`ID\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`tournament_channel\` (\`ID\` int NOT NULL AUTO_INCREMENT, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`channelID\` varchar(255) NOT NULL, \`channelType\` enum ('0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11') NOT NULL DEFAULT '0', \`createdByID\` int NULL, \`tournamentID\` int NULL, PRIMARY KEY (\`ID\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`tournament\` (\`ID\` int NOT NULL AUTO_INCREMENT, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`name\` varchar(255) NOT NULL, \`abbreviation\` varchar(255) NOT NULL, \`description\` varchar(255) NOT NULL, \`server\` varchar(255) NOT NULL, \`year\` year NOT NULL, \`matchSize\` int NOT NULL, \`regSortOrder\` enum ('0', '1', '2', '3') NOT NULL DEFAULT '0', \`isOpen\` tinyint NOT NULL DEFAULT 0, \`isClosed\` tinyint NOT NULL DEFAULT 0, \`invitational\` tinyint NOT NULL DEFAULT 0, \`minTeamSize\` int NOT NULL, \`maxTeamSize\` int NOT NULL, \`publicQualifiers\` tinyint NOT NULL DEFAULT 0, \`status\` enum ('0', '1', '2', '3') NOT NULL DEFAULT '0', \`organizerID\` int NULL, \`modeID\` int NOT NULL, \`registrationsStart\` datetime NOT NULL, \`registrationsEnd\` datetime NOT NULL, PRIMARY KEY (\`ID\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`stage\` (\`ID\` int NOT NULL AUTO_INCREMENT, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`name\` varchar(255) NOT NULL, \`abbreviation\` varchar(255) NOT NULL, \`order\` int NOT NULL, \`stageType\` enum ('0', '1', '2', '3', '4') NOT NULL DEFAULT '2', \`scoringMethod\` enum ('0', '1', '2', '3', '4', '5', '6', '7') NOT NULL DEFAULT '1', \`isFinished\` tinyint NOT NULL DEFAULT 0, \`initialSize\` int NOT NULL, \`finalSize\` int NOT NULL, \`createdByID\` int NULL, \`tournamentID\` int NULL, \`timespanStart\` datetime NOT NULL, \`timespanEnd\` datetime NOT NULL, PRIMARY KEY (\`ID\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`round\` (\`ID\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`abbreviation\` varchar(255) NOT NULL, \`stageID\` int NULL, PRIMARY KEY (\`ID\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`mappool\` (\`ID\` int NOT NULL AUTO_INCREMENT, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`name\` varchar(255) NOT NULL, \`abbreviation\` varchar(255) NOT NULL, \`isPublic\` tinyint NOT NULL DEFAULT 0, \`targetSR\` int NOT NULL, \`order\` int NOT NULL, \`createdByID\` int NULL, \`stageID\` int NULL, \`roundID\` int NULL, PRIMARY KEY (\`ID\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`mappool_slot\` (\`ID\` int NOT NULL AUTO_INCREMENT, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`name\` varchar(255) NOT NULL, \`acronym\` varchar(255) NOT NULL, \`colour\` varchar(255) NULL, \`allowedMods\` int NULL, \`userModCount\` int NULL, \`uniqueModCount\` int NULL, \`createdByID\` int NULL, \`mappoolID\` int NULL, PRIMARY KEY (\`ID\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`custom_beatmap\` (\`ID\` int NOT NULL AUTO_INCREMENT, \`link\` varchar(255) NULL, \`artist\` varchar(255) NOT NULL, \`title\` varchar(255) NOT NULL, \`BPM\` double NOT NULL, \`totalLength\` int NOT NULL, \`hitLength\` int NOT NULL, \`difficulty\` varchar(255) NOT NULL, \`circleSize\` double NOT NULL, \`overallDifficulty\` double NOT NULL, \`approachRate\` double NOT NULL, \`hpDrain\` double NOT NULL, \`circles\` int NOT NULL, \`sliders\` int NOT NULL, \`spinners\` int NOT NULL, \`maxCombo\` int NULL, \`aimSR\` double NULL, \`speedSR\` double NULL, \`totalSR\` double NOT NULL, \`modeID\` int NOT NULL, PRIMARY KEY (\`ID\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`mappool_map\` (\`ID\` int NOT NULL AUTO_INCREMENT, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`lastUpdate\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP(), \`customThreadID\` varchar(255) NULL, \`customMessageID\` varchar(255) NULL, \`order\` int NOT NULL, \`isCustom\` tinyint NOT NULL DEFAULT 0, \`deadline\` datetime NULL, \`createdByID\` int NULL, \`assignedByID\` int NULL, \`slotID\` int NULL, \`customBeatmapID\` int NULL, \`beatmapID\` int NULL, UNIQUE INDEX \`REL_f2a674f55174c09d84e35887e4\` (\`customBeatmapID\`), PRIMARY KEY (\`ID\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`mappool_map_custom_mappers_user\` (\`mappoolMapID\` int NOT NULL, \`userID\` int NOT NULL, INDEX \`IDX_dbc2f0c81e7df807af9393ef6f\` (\`mappoolMapID\`), INDEX \`IDX_3fdb2430069bc36ddfed9281b8\` (\`userID\`), PRIMARY KEY (\`mappoolMapID\`, \`userID\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`nomination\` MODIFY \`lastReviewedAt\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`mca\` MODIFY \`results\` datetime NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`mca\` MODIFY \`nominationStart\` datetime NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`mca\` MODIFY \`nominationEnd\` datetime NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`mca\` MODIFY \`votingStart\` datetime NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`mca\` MODIFY \`votingEnd\` datetime NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` MODIFY \`lastLogin\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`user\` MODIFY \`discordLastverified\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`user\` MODIFY \`osuLastverified\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`demerit_report\` MODIFY \`reportDate\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`mappool_map_history\` ADD CONSTRAINT \`FK_f2a5ef6ded9551679af2de6e05b\` FOREIGN KEY (\`createdByID\`) REFERENCES \`user\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`mappool_map_history\` ADD CONSTRAINT \`FK_4d71cb55c73a73e235eaa941a02\` FOREIGN KEY (\`mappoolMapID\`) REFERENCES \`mappool_map\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`mappool_map_history\` ADD CONSTRAINT \`FK_91a744d2af0297ac7551a4e0061\` FOREIGN KEY (\`beatmapID\`) REFERENCES \`beatmap\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`mappool_map_skill\` ADD CONSTRAINT \`FK_0822af5af607323fcae9a3a8b01\` FOREIGN KEY (\`userID\`) REFERENCES \`user\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`mappool_map_skill\` ADD CONSTRAINT \`FK_40c169a892e09dd925312b5d3ed\` FOREIGN KEY (\`mappoolMapID\`) REFERENCES \`mappool_map\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`mappool_map_weight\` ADD CONSTRAINT \`FK_451d2d1f81dc355dcf49f3839f5\` FOREIGN KEY (\`userID\`) REFERENCES \`user\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`mappool_map_weight\` ADD CONSTRAINT \`FK_0e04c219d2aaed067c03f3eb405\` FOREIGN KEY (\`mappoolMapID\`) REFERENCES \`mappool_map\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tournament_role\` ADD CONSTRAINT \`FK_3d7980b021649df8957d852d602\` FOREIGN KEY (\`createdByID\`) REFERENCES \`user\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tournament_role\` ADD CONSTRAINT \`FK_6e42fb6285926f58915731a9476\` FOREIGN KEY (\`tournamentID\`) REFERENCES \`tournament\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tournament_channel\` ADD CONSTRAINT \`FK_9477807d96ff1c5e0489299f422\` FOREIGN KEY (\`createdByID\`) REFERENCES \`user\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tournament_channel\` ADD CONSTRAINT \`FK_ea3314cdbf262c321984d9c16a0\` FOREIGN KEY (\`tournamentID\`) REFERENCES \`tournament\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tournament\` ADD CONSTRAINT \`FK_d837b180632c18af2322e473866\` FOREIGN KEY (\`organizerID\`) REFERENCES \`user\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tournament\` ADD CONSTRAINT \`FK_455742ff36fcbce4559734de6c0\` FOREIGN KEY (\`modeID\`) REFERENCES \`mode_division\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`stage\` ADD CONSTRAINT \`FK_c31ffe63e6de6c2718ae92a7422\` FOREIGN KEY (\`createdByID\`) REFERENCES \`user\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`stage\` ADD CONSTRAINT \`FK_40a84786ce719424b15ab38e9c7\` FOREIGN KEY (\`tournamentID\`) REFERENCES \`tournament\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`round\` ADD CONSTRAINT \`FK_d1a278fd1c02d08ffb984189af0\` FOREIGN KEY (\`stageID\`) REFERENCES \`stage\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`mappool\` ADD CONSTRAINT \`FK_12804c33b7cb1323ee54a9ae10e\` FOREIGN KEY (\`createdByID\`) REFERENCES \`user\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`mappool\` ADD CONSTRAINT \`FK_1542f1d5547fb8e2142309fbcf8\` FOREIGN KEY (\`stageID\`) REFERENCES \`stage\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`mappool\` ADD CONSTRAINT \`FK_f551a91a9c1a906a0c5937ac3ab\` FOREIGN KEY (\`roundID\`) REFERENCES \`round\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`mappool_slot\` ADD CONSTRAINT \`FK_9bb2035c81dbe73e1f715b34641\` FOREIGN KEY (\`createdByID\`) REFERENCES \`user\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`mappool_slot\` ADD CONSTRAINT \`FK_db1501100e2089e602531eb050b\` FOREIGN KEY (\`mappoolID\`) REFERENCES \`mappool\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`custom_beatmap\` ADD CONSTRAINT \`FK_c7e029bfab72ca6ee17f56cf44f\` FOREIGN KEY (\`modeID\`) REFERENCES \`mode_division\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`mappool_map\` ADD CONSTRAINT \`FK_f7a0bafbeca589f8a546bcc525c\` FOREIGN KEY (\`createdByID\`) REFERENCES \`user\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`mappool_map\` ADD CONSTRAINT \`FK_e3e864f476ad3dcc0ca29d1c43e\` FOREIGN KEY (\`assignedByID\`) REFERENCES \`user\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`mappool_map\` ADD CONSTRAINT \`FK_e0fd6bfacfd88cbd77e4983689d\` FOREIGN KEY (\`slotID\`) REFERENCES \`mappool_slot\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`mappool_map\` ADD CONSTRAINT \`FK_f2a674f55174c09d84e35887e41\` FOREIGN KEY (\`customBeatmapID\`) REFERENCES \`custom_beatmap\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`mappool_map\` ADD CONSTRAINT \`FK_765b31ee40f1084971908109359\` FOREIGN KEY (\`beatmapID\`) REFERENCES \`beatmap\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`mappool_map_custom_mappers_user\` ADD CONSTRAINT \`FK_dbc2f0c81e7df807af9393ef6fe\` FOREIGN KEY (\`mappoolMapID\`) REFERENCES \`mappool_map\`(\`ID\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`mappool_map_custom_mappers_user\` ADD CONSTRAINT \`FK_3fdb2430069bc36ddfed9281b82\` FOREIGN KEY (\`userID\`) REFERENCES \`user\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`CREATE TABLE \`mappool_map_testplayers_user\` (\`mappoolMapID\` int NOT NULL, \`userID\` int NOT NULL, INDEX \`IDX_9fb22398fe1bcf3f221500332a\` (\`mappoolMapID\`), INDEX \`IDX_9c572787cda37b6e271ae158e6\` (\`userID\`), PRIMARY KEY (\`mappoolMapID\`, \`userID\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`mappool_map_testplayers_user\` ADD CONSTRAINT \`FK_9fb22398fe1bcf3f221500332ad\` FOREIGN KEY (\`mappoolMapID\`) REFERENCES \`mappool_map\`(\`ID\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`mappool_map_testplayers_user\` ADD CONSTRAINT \`FK_9c572787cda37b6e271ae158e68\` FOREIGN KEY (\`userID\`) REFERENCES \`user\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down (queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`mappool_map_testplayers_user\` DROP FOREIGN KEY \`FK_9c572787cda37b6e271ae158e68\``);
        await queryRunner.query(`ALTER TABLE \`mappool_map_testplayers_user\` DROP FOREIGN KEY \`FK_9fb22398fe1bcf3f221500332ad\``);
        await queryRunner.query(`DROP INDEX \`IDX_9c572787cda37b6e271ae158e6\` ON \`mappool_map_testplayers_user\``);
        await queryRunner.query(`DROP INDEX \`IDX_9fb22398fe1bcf3f221500332a\` ON \`mappool_map_testplayers_user\``);
        await queryRunner.query(`DROP TABLE \`mappool_map_testplayers_user\``);
        await queryRunner.query(`ALTER TABLE \`mappool_map_custom_mappers_user\` DROP FOREIGN KEY \`FK_3fdb2430069bc36ddfed9281b82\``);
        await queryRunner.query(`ALTER TABLE \`mappool_map_custom_mappers_user\` DROP FOREIGN KEY \`FK_dbc2f0c81e7df807af9393ef6fe\``);
        await queryRunner.query(`ALTER TABLE \`mappool_map\` DROP FOREIGN KEY \`FK_765b31ee40f1084971908109359\``);
        await queryRunner.query(`ALTER TABLE \`mappool_map\` DROP FOREIGN KEY \`FK_f2a674f55174c09d84e35887e41\``);
        await queryRunner.query(`ALTER TABLE \`mappool_map\` DROP FOREIGN KEY \`FK_e0fd6bfacfd88cbd77e4983689d\``);
        await queryRunner.query(`ALTER TABLE \`mappool_map\` DROP FOREIGN KEY \`FK_e3e864f476ad3dcc0ca29d1c43e\``);
        await queryRunner.query(`ALTER TABLE \`mappool_map\` DROP FOREIGN KEY \`FK_f7a0bafbeca589f8a546bcc525c\``);
        await queryRunner.query(`ALTER TABLE \`custom_beatmap\` DROP FOREIGN KEY \`FK_c7e029bfab72ca6ee17f56cf44f\``);
        await queryRunner.query(`ALTER TABLE \`mappool_slot\` DROP FOREIGN KEY \`FK_db1501100e2089e602531eb050b\``);
        await queryRunner.query(`ALTER TABLE \`mappool_slot\` DROP FOREIGN KEY \`FK_9bb2035c81dbe73e1f715b34641\``);
        await queryRunner.query(`ALTER TABLE \`mappool\` DROP FOREIGN KEY \`FK_f551a91a9c1a906a0c5937ac3ab\``);
        await queryRunner.query(`ALTER TABLE \`mappool\` DROP FOREIGN KEY \`FK_1542f1d5547fb8e2142309fbcf8\``);
        await queryRunner.query(`ALTER TABLE \`mappool\` DROP FOREIGN KEY \`FK_12804c33b7cb1323ee54a9ae10e\``);
        await queryRunner.query(`ALTER TABLE \`round\` DROP FOREIGN KEY \`FK_d1a278fd1c02d08ffb984189af0\``);
        await queryRunner.query(`ALTER TABLE \`stage\` DROP FOREIGN KEY \`FK_40a84786ce719424b15ab38e9c7\``);
        await queryRunner.query(`ALTER TABLE \`stage\` DROP FOREIGN KEY \`FK_c31ffe63e6de6c2718ae92a7422\``);
        await queryRunner.query(`ALTER TABLE \`tournament\` DROP FOREIGN KEY \`FK_455742ff36fcbce4559734de6c0\``);
        await queryRunner.query(`ALTER TABLE \`tournament\` DROP FOREIGN KEY \`FK_d837b180632c18af2322e473866\``);
        await queryRunner.query(`ALTER TABLE \`tournament_channel\` DROP FOREIGN KEY \`FK_ea3314cdbf262c321984d9c16a0\``);
        await queryRunner.query(`ALTER TABLE \`tournament_channel\` DROP FOREIGN KEY \`FK_9477807d96ff1c5e0489299f422\``);
        await queryRunner.query(`ALTER TABLE \`tournament_role\` DROP FOREIGN KEY \`FK_6e42fb6285926f58915731a9476\``);
        await queryRunner.query(`ALTER TABLE \`tournament_role\` DROP FOREIGN KEY \`FK_3d7980b021649df8957d852d602\``);
        await queryRunner.query(`ALTER TABLE \`mappool_map_weight\` DROP FOREIGN KEY \`FK_0e04c219d2aaed067c03f3eb405\``);
        await queryRunner.query(`ALTER TABLE \`mappool_map_weight\` DROP FOREIGN KEY \`FK_451d2d1f81dc355dcf49f3839f5\``);
        await queryRunner.query(`ALTER TABLE \`mappool_map_skill\` DROP FOREIGN KEY \`FK_40c169a892e09dd925312b5d3ed\``);
        await queryRunner.query(`ALTER TABLE \`mappool_map_skill\` DROP FOREIGN KEY \`FK_0822af5af607323fcae9a3a8b01\``);
        await queryRunner.query(`ALTER TABLE \`mappool_map_history\` DROP FOREIGN KEY \`FK_91a744d2af0297ac7551a4e0061\``);
        await queryRunner.query(`ALTER TABLE \`mappool_map_history\` DROP FOREIGN KEY \`FK_4d71cb55c73a73e235eaa941a02\``);
        await queryRunner.query(`ALTER TABLE \`mappool_map_history\` DROP FOREIGN KEY \`FK_f2a5ef6ded9551679af2de6e05b\``);
        await queryRunner.query(`ALTER TABLE \`demerit_report\` MODIFY \`reportDate\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`user\` MODIFY \`osuLastverified\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`user\` MODIFY \`discordLastverified\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`user\` MODIFY \`lastLogin\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`mca\` MODIFY \`votingEnd\` timestamp NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`mca\` MODIFY \`votingStart\` timestamp NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`mca\` MODIFY \`nominationEnd\` timestamp NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`mca\` MODIFY \`nominationStart\` timestamp NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`mca\` MODIFY \`results\` timestamp NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`nomination\` MODIFY \`lastReviewedAt\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`DROP INDEX \`IDX_3fdb2430069bc36ddfed9281b8\` ON \`mappool_map_custom_mappers_user\``);
        await queryRunner.query(`DROP INDEX \`IDX_dbc2f0c81e7df807af9393ef6f\` ON \`mappool_map_custom_mappers_user\``);
        await queryRunner.query(`DROP TABLE \`mappool_map_custom_mappers_user\``);
        await queryRunner.query(`DROP INDEX \`REL_f2a674f55174c09d84e35887e4\` ON \`mappool_map\``);
        await queryRunner.query(`DROP TABLE \`mappool_map\``);
        await queryRunner.query(`DROP TABLE \`custom_beatmap\``);
        await queryRunner.query(`DROP TABLE \`mappool_slot\``);
        await queryRunner.query(`DROP TABLE \`mappool\``);
        await queryRunner.query(`DROP TABLE \`round\``);
        await queryRunner.query(`DROP TABLE \`stage\``);
        await queryRunner.query(`DROP TABLE \`tournament\``);
        await queryRunner.query(`DROP TABLE \`tournament_channel\``);
        await queryRunner.query(`DROP TABLE \`tournament_role\``);
        await queryRunner.query(`DROP TABLE \`mappool_map_weight\``);
        await queryRunner.query(`DROP TABLE \`mappool_map_skill\``);
        await queryRunner.query(`DROP TABLE \`mappool_map_history\``);
        await queryRunner.query(`ALTER TABLE \`user_nominations_nomination\` ADD CONSTRAINT \`FK_c39e90811e78d3a759f9f75e37c\` FOREIGN KEY (\`userID\`) REFERENCES \`user\`(\`ID\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_nominations_nomination\` ADD CONSTRAINT \`FK_2dc37a0c6b4f99e6e20c4903ae0\` FOREIGN KEY (\`nominationID\`) REFERENCES \`nomination\`(\`ID\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
