import ormConfig from "../../ormconfig";
import { MCA } from "../../Models/MCA_AYIM/mca";
import { ModeDivision } from "../../Models/MCA_AYIM/modeDivision";
import { CategoryFilter, CategoryGenerator } from "../../Models/MCA_AYIM/category";
import { CategoryType } from "../../Interfaces/category";
import { exit } from "process";
import { sleep } from "../utils/sleep";

const mca2021Categories: {
    name: string,
    type: CategoryType,
    modeName: string,
    filter: CategoryFilter,
}[] = [{
    "name": "collab",
    "type": 0,
    "modeName": "standard",
    "filter": {
        "minLength": null,
        "maxLength": null,
        "minBPM": null,
        "maxBPM": null,
        "minSR": null,
        "maxSR": null,
        "minCS": null,
        "maxCS": null,
        "topOnly": false,
        "rookie": null,
    },
}, {
    "name": "complex",
    "type": 0,
    "modeName": "standard",
    "filter": {
        "minLength": null,
        "maxLength": null,
        "minBPM": null,
        "maxBPM": null,
        "minSR": null,
        "maxSR": null,
        "minCS": null,
        "maxCS": null,
        "topOnly": false,
        "rookie": null,
    },
}, {
    "name": "highBPMAlternator",
    "type": 0,
    "modeName": "standard",
    "filter": {
        "minLength": null,
        "maxLength": null,
        "minBPM": null,
        "maxBPM": null,
        "minSR": null,
        "maxSR": null,
        "minCS": null,
        "maxCS": null,
        "topOnly": false,
        "rookie": null,
    },
}, {
    "name": "hitsounder",
    "type": 1,
    "modeName": "standard",
    "filter": {
        "minLength": null,
        "maxLength": null,
        "minBPM": null,
        "maxBPM": null,
        "minSR": null,
        "maxSR": null,
        "minCS": null,
        "maxCS": null,
        "topOnly": false,
        "rookie": null,
    },
}, {
    "name": "hitsounding",
    "type": 0,
    "modeName": "standard",
    "filter": {
        "minLength": null,
        "maxLength": null,
        "minBPM": null,
        "maxBPM": null,
        "minSR": null,
        "maxSR": null,
        "minCS": null,
        "maxCS": null,
        "topOnly": true,
        "rookie": null,
    },
}, {
    "name": "mapper",
    "type": 1,
    "modeName": "standard",
    "filter": {
        "minLength": null,
        "maxLength": null,
        "minBPM": null,
        "maxBPM": null,
        "minSR": null,
        "maxSR": null,
        "minCS": null,
        "maxCS": null,
        "topOnly": false,
        "rookie": null,
    },
}, {
    "name": "marathon",
    "type": 0,
    "modeName": "standard",
    "filter": {
        "minLength": 270,
        "maxLength": null,
        "minBPM": null,
        "maxBPM": null,
        "minSR": null,
        "maxSR": null,
        "minCS": null,
        "maxCS": null,
        "topOnly": false,
        "rookie": null,
    },
}, {
    "name": "modder",
    "type": 1,
    "modeName": "standard",
    "filter": {
        "minLength": null,
        "maxLength": null,
        "minBPM": null,
        "maxBPM": null,
        "minSR": null,
        "maxSR": null,
        "minCS": null,
        "maxCS": null,
        "topOnly": false,
        "rookie": null,
    },
}, {
    "name": "mostPromising",
    "type": 1,
    "modeName": "standard",
    "filter": {
        "minLength": null,
        "maxLength": null,
        "minBPM": null,
        "maxBPM": null,
        "minSR": null,
        "maxSR": null,
        "minCS": null,
        "maxCS": null,
        "topOnly": false,
        "rookie": true,
    },
}, {
    "name": "outCont",
    "type": 1,
    "modeName": "standard",
    "filter": {
        "minLength": null,
        "maxLength": null,
        "minBPM": null,
        "maxBPM": null,
        "minSR": null,
        "maxSR": null,
        "minCS": null,
        "maxCS": null,
        "topOnly": false,
        "rookie": null,
    },
}, {
    "name": "sliderTech",
    "type": 0,
    "modeName": "standard",
    "filter": {
        "minLength": null,
        "maxLength": null,
        "minBPM": null,
        "maxBPM": null,
        "minSR": null,
        "maxSR": null,
        "minCS": null,
        "maxCS": null,
        "topOnly": false,
        "rookie": null,
    },
}, {
    "name": "smallCircles",
    "type": 0,
    "modeName": "standard",
    "filter": {
        "minLength": null,
        "maxLength": null,
        "minBPM": null,
        "maxBPM": null,
        "minSR": null,
        "maxSR": null,
        "minCS": 5,
        "maxCS": null,
        "topOnly": false,
        "rookie": null,
    },
}, {
    "name": "unorthodox",
    "type": 0,
    "modeName": "standard",
    "filter": {
        "minLength": null,
        "maxLength": null,
        "minBPM": null,
        "maxBPM": null,
        "minSR": null,
        "maxSR": null,
        "minCS": null,
        "maxCS": null,
        "topOnly": false,
        "rookie": null,
    },
}, {
    "name": "vanilla",
    "type": 0,
    "modeName": "standard",
    "filter": {
        "minLength": null,
        "maxLength": null,
        "minBPM": null,
        "maxBPM": null,
        "minSR": null,
        "maxSR": null,
        "minCS": null,
        "maxCS": null,
        "topOnly": false,
        "rookie": null,
    },
}, {
    "name": "collab",
    "type": 0,
    "modeName": "taiko",
    "filter": {
        "minLength": null,
        "maxLength": null,
        "minBPM": null,
        "maxBPM": null,
        "minSR": null,
        "maxSR": null,
        "minCS": null,
        "maxCS": null,
        "topOnly": false,
        "rookie": null,
    },
}, {
    "name": "diversity",
    "type": 0,
    "modeName": "taiko",
    "filter": {
        "minLength": null,
        "maxLength": null,
        "minBPM": null,
        "maxBPM": null,
        "minSR": null,
        "maxSR": null,
        "minCS": null,
        "maxCS": null,
        "topOnly": false,
        "rookie": null,
    },
}, {
    "name": "featuredArtist",
    "type": 0,
    "modeName": "taiko",
    "filter": {
        "minLength": null,
        "maxLength": null,
        "minBPM": null,
        "maxBPM": null,
        "minSR": null,
        "maxSR": null,
        "minCS": null,
        "maxCS": null,
        "topOnly": false,
        "rookie": null,
    },
}, {
    "name": "highBPMTaiko",
    "type": 0,
    "modeName": "taiko",
    "filter": {
        "minLength": null,
        "maxLength": null,
        "minBPM": null,
        "maxBPM": null,
        "minSR": null,
        "maxSR": null,
        "minCS": null,
        "maxCS": null,
        "topOnly": false,
        "rookie": null,
    },
}, {
    "name": "lowBPMTaiko",
    "type": 0,
    "modeName": "taiko",
    "filter": {
        "minLength": null,
        "maxLength": null,
        "minBPM": null,
        "maxBPM": null,
        "minSR": null,
        "maxSR": null,
        "minCS": null,
        "maxCS": null,
        "topOnly": false,
        "rookie": null,
    },
}, {
    "name": "mapper",
    "type": 1,
    "modeName": "taiko",
    "filter": {
        "minLength": null,
        "maxLength": null,
        "minBPM": null,
        "maxBPM": null,
        "minSR": null,
        "maxSR": null,
        "minCS": null,
        "maxCS": null,
        "topOnly": false,
        "rookie": null,
    },
}, {
    "name": "marathon",
    "type": 0,
    "modeName": "taiko",
    "filter": {
        "minLength": 270,
        "maxLength": null,
        "minBPM": null,
        "maxBPM": null,
        "minSR": null,
        "maxSR": null,
        "minCS": null,
        "maxCS": null,
        "topOnly": false,
        "rookie": null,
    },
}, {
    "name": "modder",
    "type": 1,
    "modeName": "taiko",
    "filter": {
        "minLength": null,
        "maxLength": null,
        "minBPM": null,
        "maxBPM": null,
        "minSR": null,
        "maxSR": null,
        "minCS": null,
        "maxCS": null,
        "topOnly": false,
        "rookie": null,
    },
}, {
    "name": "mostInfluential",
    "type": 1,
    "modeName": "taiko",
    "filter": {
        "minLength": null,
        "maxLength": null,
        "minBPM": null,
        "maxBPM": null,
        "minSR": null,
        "maxSR": null,
        "minCS": null,
        "maxCS": null,
        "topOnly": false,
        "rookie": null,
    },
}, {
    "name": "mostPromising",
    "type": 1,
    "modeName": "taiko",
    "filter": {
        "minLength": null,
        "maxLength": null,
        "minBPM": null,
        "maxBPM": null,
        "minSR": null,
        "maxSR": null,
        "minCS": null,
        "maxCS": null,
        "topOnly": false,
        "rookie": true,
    },
}, {
    "name": "outCont",
    "type": 1,
    "modeName": "taiko",
    "filter": {
        "minLength": null,
        "maxLength": null,
        "minBPM": null,
        "maxBPM": null,
        "minSR": null,
        "maxSR": null,
        "minCS": null,
        "maxCS": null,
        "topOnly": false,
        "rookie": null,
    },
}, {
    "name": "simplisticTaiko",
    "type": 0,
    "modeName": "taiko",
    "filter": {
        "minLength": null,
        "maxLength": null,
        "minBPM": null,
        "maxBPM": null,
        "minSR": null,
        "maxSR": null,
        "minCS": null,
        "maxCS": null,
        "topOnly": false,
        "rookie": null,
    },
}, {
    "name": "sliderVelocity",
    "type": 0,
    "modeName": "taiko",
    "filter": {
        "minLength": null,
        "maxLength": null,
        "minBPM": null,
        "maxBPM": null,
        "minSR": null,
        "maxSR": null,
        "minCS": null,
        "maxCS": null,
        "topOnly": false,
        "rookie": null,
    },
}, {
    "name": "spread",
    "type": 0,
    "modeName": "taiko",
    "filter": {
        "minLength": null,
        "maxLength": null,
        "minBPM": null,
        "maxBPM": null,
        "minSR": null,
        "maxSR": null,
        "minCS": null,
        "maxCS": null,
        "topOnly": true,
        "rookie": null,
    },
}, {
    "name": "technicalTaiko",
    "type": 0,
    "modeName": "taiko",
    "filter": {
        "minLength": null,
        "maxLength": null,
        "minBPM": null,
        "maxBPM": null,
        "minSR": null,
        "maxSR": null,
        "minCS": null,
        "maxCS": null,
        "topOnly": false,
        "rookie": null,
    },
}, {
    "name": "antiMetaCatch",
    "type": 0,
    "modeName": "fruits",
    "filter": {
        "minLength": null,
        "maxLength": null,
        "minBPM": null,
        "maxBPM": null,
        "minSR": null,
        "maxSR": null,
        "minCS": null,
        "maxCS": null,
        "topOnly": false,
        "rookie": null,
    },
}, {
    "name": "collab",
    "type": 0,
    "modeName": "fruits",
    "filter": {
        "minLength": null,
        "maxLength": null,
        "minBPM": null,
        "maxBPM": null,
        "minSR": null,
        "maxSR": null,
        "minCS": null,
        "maxCS": null,
        "topOnly": false,
        "rookie": null,
    },
}, {
    "name": "communityPillar",
    "type": 1,
    "modeName": "fruits",
    "filter": {
        "minLength": null,
        "maxLength": null,
        "minBPM": null,
        "maxBPM": null,
        "minSR": null,
        "maxSR": null,
        "minCS": null,
        "maxCS": null,
        "topOnly": false,
        "rookie": null,
    },
}, {
    "name": "featuredArtist",
    "type": 0,
    "modeName": "fruits",
    "filter": {
        "minLength": null,
        "maxLength": null,
        "minBPM": null,
        "maxBPM": null,
        "minSR": null,
        "maxSR": null,
        "minCS": null,
        "maxCS": null,
        "topOnly": false,
        "rookie": null,
    },
}, {
    "name": "hitsounding",
    "type": 0,
    "modeName": "fruits",
    "filter": {
        "minLength": null,
        "maxLength": null,
        "minBPM": null,
        "maxBPM": null,
        "minSR": null,
        "maxSR": null,
        "minCS": null,
        "maxCS": null,
        "topOnly": true,
        "rookie": null,
    },
}, {
    "name": "mapper",
    "type": 1,
    "modeName": "fruits",
    "filter": {
        "minLength": null,
        "maxLength": null,
        "minBPM": null,
        "maxBPM": null,
        "minSR": null,
        "maxSR": null,
        "minCS": null,
        "maxCS": null,
        "topOnly": false,
        "rookie": null,
    },
}, {
    "name": "marathon",
    "type": 0,
    "modeName": "fruits",
    "filter": {
        "minLength": 270,
        "maxLength": null,
        "minBPM": null,
        "maxBPM": null,
        "minSR": null,
        "maxSR": null,
        "minCS": null,
        "maxCS": null,
        "topOnly": false,
        "rookie": null,
    },
}, {
    "name": "modder",
    "type": 1,
    "modeName": "fruits",
    "filter": {
        "minLength": null,
        "maxLength": null,
        "minBPM": null,
        "maxBPM": null,
        "minSR": null,
        "maxSR": null,
        "minCS": null,
        "maxCS": null,
        "topOnly": false,
        "rookie": null,
    },
}, {
    "name": "mostInspiring",
    "type": 1,
    "modeName": "fruits",
    "filter": {
        "minLength": null,
        "maxLength": null,
        "minBPM": null,
        "maxBPM": null,
        "minSR": null,
        "maxSR": null,
        "minCS": null,
        "maxCS": null,
        "topOnly": false,
        "rookie": null,
    },
}, {
    "name": "mostPromising",
    "type": 1,
    "modeName": "fruits",
    "filter": {
        "minLength": null,
        "maxLength": null,
        "minBPM": null,
        "maxBPM": null,
        "minSR": null,
        "maxSR": null,
        "minCS": null,
        "maxCS": null,
        "topOnly": false,
        "rookie": true,
    },
}, {
    "name": "simplistic",
    "type": 0,
    "modeName": "fruits",
    "filter": {
        "minLength": null,
        "maxLength": null,
        "minBPM": null,
        "maxBPM": null,
        "minSR": null,
        "maxSR": null,
        "minCS": null,
        "maxCS": null,
        "topOnly": false,
        "rookie": null,
    },
}, {
    "name": "spread",
    "type": 0,
    "modeName": "fruits",
    "filter": {
        "minLength": null,
        "maxLength": null,
        "minBPM": null,
        "maxBPM": null,
        "minSR": null,
        "maxSR": null,
        "minCS": null,
        "maxCS": null,
        "topOnly": true,
        "rookie": null,
    },
}, {
    "name": "technicalCatch",
    "type": 0,
    "modeName": "fruits",
    "filter": {
        "minLength": null,
        "maxLength": null,
        "minBPM": null,
        "maxBPM": null,
        "minSR": null,
        "maxSR": null,
        "minCS": null,
        "maxCS": null,
        "topOnly": false,
        "rookie": null,
    },
}, {
    "name": "7K",
    "type": 0,
    "modeName": "mania",
    "filter": {
        "minLength": null,
        "maxLength": null,
        "minBPM": null,
        "maxBPM": null,
        "minSR": null,
        "maxSR": null,
        "minCS": null,
        "maxCS": null,
        "topOnly": false,
        "rookie": null,
    },
}, {
    "name": "antiMeta",
    "type": 0,
    "modeName": "mania",
    "filter": {
        "minLength": null,
        "maxLength": null,
        "minBPM": null,
        "maxBPM": null,
        "minSR": null,
        "maxSR": null,
        "minCS": null,
        "maxCS": null,
        "topOnly": false,
        "rookie": null,
    },
}, {
    "name": "hitsounding",
    "type": 0,
    "modeName": "mania",
    "filter": {
        "minLength": null,
        "maxLength": null,
        "minBPM": null,
        "maxBPM": null,
        "minSR": null,
        "maxSR": null,
        "minCS": null,
        "maxCS": null,
        "topOnly": true,
        "rookie": null,
    },
}, {
    "name": "hybrid",
    "type": 0,
    "modeName": "mania",
    "filter": {
        "minLength": null,
        "maxLength": null,
        "minBPM": null,
        "maxBPM": null,
        "minSR": null,
        "maxSR": null,
        "minCS": null,
        "maxCS": null,
        "topOnly": false,
        "rookie": null,
    },
}, {
    "name": "longNotes",
    "type": 0,
    "modeName": "mania",
    "filter": {
        "minLength": null,
        "maxLength": null,
        "minBPM": null,
        "maxBPM": null,
        "minSR": null,
        "maxSR": null,
        "minCS": null,
        "maxCS": null,
        "topOnly": false,
        "rookie": null,
    },
}, {
    "name": "mapper",
    "type": 1,
    "modeName": "mania",
    "filter": {
        "minLength": null,
        "maxLength": null,
        "minBPM": null,
        "maxBPM": null,
        "minSR": null,
        "maxSR": null,
        "minCS": null,
        "maxCS": null,
        "topOnly": false,
        "rookie": null,
    },
}, {
    "name": "marathon",
    "type": 0,
    "modeName": "mania",
    "filter": {
        "minLength": 240,
        "maxLength": null,
        "minBPM": null,
        "maxBPM": null,
        "minSR": null,
        "maxSR": null,
        "minCS": null,
        "maxCS": null,
        "topOnly": false,
        "rookie": null,
    },
}, {
    "name": "modder",
    "type": 1,
    "modeName": "mania",
    "filter": {
        "minLength": null,
        "maxLength": null,
        "minBPM": null,
        "maxBPM": null,
        "minSR": null,
        "maxSR": null,
        "minCS": null,
        "maxCS": null,
        "topOnly": false,
        "rookie": null,
    },
}, {
    "name": "mostInfluential",
    "type": 1,
    "modeName": "mania",
    "filter": {
        "minLength": null,
        "maxLength": null,
        "minBPM": null,
        "maxBPM": null,
        "minSR": null,
        "maxSR": null,
        "minCS": null,
        "maxCS": null,
        "topOnly": false,
        "rookie": null,
    },
}, {
    "name": "mostPromising",
    "type": 1,
    "modeName": "mania",
    "filter": {
        "minLength": null,
        "maxLength": null,
        "minBPM": null,
        "maxBPM": null,
        "minSR": null,
        "maxSR": null,
        "minCS": null,
        "maxCS": null,
        "topOnly": false,
        "rookie": true,
    },
}, {
    "name": "sliderVelocity",
    "type": 0,
    "modeName": "mania",
    "filter": {
        "minLength": null,
        "maxLength": null,
        "minBPM": null,
        "maxBPM": null,
        "minSR": null,
        "maxSR": null,
        "minCS": null,
        "maxCS": null,
        "topOnly": false,
        "rookie": null,
    },
}, {
    "name": "spread",
    "type": 0,
    "modeName": "mania",
    "filter": {
        "minLength": null,
        "maxLength": null,
        "minBPM": null,
        "maxBPM": null,
        "minSR": null,
        "maxSR": null,
        "minCS": null,
        "maxCS": null,
        "topOnly": true,
        "rookie": null,
    },
}] ;

ormConfig.initialize().then(async () => {
    let mca = await MCA.findOne({
        where: {
            year: 2021,
        },
    });
    if (mca) {
        console.log("\x1b[41;1mMCA 2021 already exists!\x1b[0m");
        exit(0);
    }

    console.log("\x1b[43;1mWARNING: This script is for development purposes only.\x1b[0m\nThis will create a new MCA 2021 with all of the categories used in the official MCA 2021.\nScript will start in 5 seconds.");
    await sleep(5000);

    mca = await MCA.fillAndSave({
        year: 2021,
        nominationStart: new Date(),
        nominationEnd: new Date(Date.now() + 1000 * 60 * 60 * 24 * 7),
        votingStart: new Date(Date.now() + 1000 * 60 * 60 * 24 * 7 * 2),
        votingEnd: new Date(Date.now() + 1000 * 60 * 60 * 24 * 7 * 4),
        results: new Date(Date.now() + 1000 * 60 * 60 * 24 * 7 * 5),
    });

    const modes = await ModeDivision.find();
    const categoryGenerator = new CategoryGenerator();
    for (const mode of modes) {
        const userGrand = categoryGenerator.createGrandAward(mca, mode, CategoryType.Users, mode.name === "storyboard");
        const mapGrand = categoryGenerator.createGrandAward(mca, mode, CategoryType.Beatmapsets, mode.name === "storyboard");
        const categories = [userGrand.save(), mapGrand.save()];

        mca2021Categories.filter(c => c.modeName === mode.name).forEach(c => {
            const category = categoryGenerator.createOrUpdate({
                name: c.name,
                maxNominations: 3,
                type: c.type,
                mode: mode,
                mca: mca!,
            }, c.filter);
            categories.push(category.save());
        });

        await Promise.all(categories);
    }

    console.log("\x1b[42;1mMCA 2021 created!\x1b[0m");
    exit(0);
}).catch(console.error);