apiVersion: v1
kind: Secret
metadata:
  name: {{ include "corsace-chart.fullname" . }}
  labels:
    {{- include "corsace-chart.labels" . | nindent 4 }}
type: Opaque
data:
  databaseHost: {{ required "database host is required" .Values.secrets.database.host | b64enc }}
  discordToken: {{ required "Discord token is required" .Values.secrets.discord.token | b64enc }}
  discordClientSecret: {{ required "Discord client secret is required" .Values.secrets.discord.clientSecret | b64enc }}
  googleCredentialsPrivateKey: {{ required "Google credentials private key is required" .Values.secrets.google.credentials.privateKey | b64enc }}
  googleCredentialsClientEmail: {{ required "Google credentials client email is required" .Values.secrets.google.credentials.clientEmail | b64enc }}
  googleSheetsTodo: {{ required "Google Sheets todo sheet id is required" .Values.secrets.google.sheets.todo | b64enc }}
  googleSheetsOpenMappool: {{ required "Google Sheets open mappool sheet id is required" .Values.secrets.google.sheets.openMappool | b64enc }}
  googleSheetsClosedMappool: {{ required "Google Sheets closed mappool sheet id is required" .Values.secrets.google.sheets.closedMappool | b64enc }}
  googleSheetsSongs: {{ required "Google Sheets songs sheet id is required" .Values.secrets.google.sheets.songs | b64enc }}
  osuv1ApiKey: {{ required "osu! v1 api key is required" .Values.secrets.osu.v1.apiKey | b64enc }}
  osuv2ClientId: {{ required "osu! v2 client id is required" .Values.secrets.osu.v2.clientId | b64enc }}
  osuv2ClientSecret: {{ required "osu! v2 client secret is required" .Values.secrets.osu.v2.clientSecret | b64enc }}
  koaKey: {{ required "koa key is required" .Values.secrets.koaKey | b64enc }}
  interOpPassword: {{ required "interop password is required" .Values.secrets.interOpPassword | b64enc }}
  bnUsername: {{ required "bn username is required" .Values.secrets.bnUsername | b64enc }}
  bnSecret: {{ required "bn secret is required" .Values.secrets.bnSecret | b64enc }}
  cloudflareR2Hostname: {{ required "cloudflare r2 hostname is required" .Values.secrets.cloudflareR2Hostname | b64enc }}
  cloudflareR2AccessKeyId: {{ required "cloudflare r2 username is required" .Values.secrets.cloudflareR2AccessKeyId | b64enc }}
  cloudflareR2SecretAccessKey: {{ required "cloudflare r2 password is required" .Values.secrets.cloudflareR2SecretAccessKey | b64enc }}
