{{- range $webServiceName, $webService := .Values.webServices }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "corsace-chart.fullname" $ }}-{{ lower $webServiceName }}
  labels:
    {{- include "corsace-chart.labels" $ | nindent 4 }}
spec:
  type: {{ $.Values.service.type }}
  ports:
    - port: {{ $.Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    webServiceName: {{ $webServiceName }}
{{- end }}